## ----------------------------------------------------------------------------------------------------
## 작성목적 : jeju-backend 백엔드 애플리케이션 빌드/배포용 AWS CodeBuild 스펙
## 작성일 : 2025-12-02
##
## 변경사항 내역 (날짜 | 변경목적 | 변경내용 | 작성자 순으로 기입)
## 2025-12-02 | 최초 구현 | 기본 buildspec-backend.yml 스캐폴딩 생성 | 이재인
## ----------------------------------------------------------------------------------------------------

version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn -f pom.xml clean package -DskipTests

artifacts:
  files:
    - target/*.jar


